-- Demo rows so local /api/v1/offers is never empty after migrations.
-- Replace with real crawl data in production.

INSERT INTO source (id, name, country_code, type, base_url, crawl_enabled, refresh_interval_min, robots_compliant, created_at, updated_at)
VALUES (
    'a0000001-0000-0000-0000-000000000001'::uuid,
    'Rebike DE (Dev Seed)',
    'DE',
    'refurbisher',
    'https://www.rebike.de',
    true,
    720,
    true,
    now(),
    now()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO bike_offer (
    id,
    source_id,
    source_offer_id,
    source_url,
    status,
    brand,
    model,
    model_year,
    bike_category,
    bike_condition,
    warranty_type,
    warranty_months,
    motor_brand,
    motor_model,
    motor_position,
    battery_wh,
    mileage_km,
    list_price_local,
    currency_code,
    total_price_local,
    price_chf,
    shipping_estimate_chf,
    import_surcharge_chf,
    landed_price_chf,
    swiss_median_price_chf,
    discount_vs_swiss_pct,
    is_bargain,
    quality_score,
    images,
    extraction_method,
    first_seen_at,
    last_seen_at,
    created_at,
    updated_at
)
VALUES (
    'b0000001-0000-0000-0000-000000000001'::uuid,
    'a0000001-0000-0000-0000-000000000001'::uuid,
    'dev-seed-001',
    'https://example.com/europebikefinder/dev-listing',
    'active',
    'Specialized',
    'Turbo Vado 4.0',
    2023,
    'city',
    'refurbished',
    'certified_refurb',
    12,
    'Bosch',
    'Performance Line',
    'mid',
    500,
    1200,
    2200.00,
    'EUR',
    2200.00,
    2100.00,
    0.00,
    150.00,
    2450.00,
    3400.00,
    27.94,
    true,
    8.5,
    ARRAY['https://placehold.co/640x400/png?text=E-Bike+Dev']::text[],
    'heuristic',
    now(),
    now(),
    now(),
    now()
)
ON CONFLICT (source_id, source_offer_id) DO NOTHING;
